frontend/webapp/blueprints/sizing.py
from flask import Blueprint, render_template, redirect, url_for
from extensions import user_info_wrapper

sizing_blueprint = Blueprint('sizing', __name__)

@sizing_blueprint.route('/')
def home():
	return redirect(url_for('sizing.compute'))

@sizing_blueprint.route('/microgrids/', defaults={"id":None})
@sizing_blueprint.route('/microgrids/<id>/')
@user_info_wrapper
def grids(username, role, id):
	if id is not None:
		return render_template(
			'tools/sizing/grid.html', 
			username=username, 
			role=role, 
			active_page='sizing',
			active_sub_page='grids',
			id=id,
		)
	return render_template(
		'tools/sizing/grids.html',
		username=username, 
		role=role, 
		active_page='sizing',
		active_sub_page='grids'
  	)

@sizing_blueprint.route('/compute/')
@user_info_wrapper
def compute(username, role):
	return render_template(
		'tools/sizing/compute.html', 
		username=username, 
		role=role, 
		active_page='sizing', 
		active_sub_page='compute'
	)

@sizing_blueprint.route('/results/', defaults={"id":None})
@sizing_blueprint.route('/results/<id>/')
@user_info_wrapper
def results(username, role, id):
	if id is not None:
		return render_template(
				'tools/sizing/result.html', 
				username=username, 
				role=role, 
				active_page='sizing', 
				active_sub_page='results',
				id=id,
			)
	return render_template(
			'tools/sizing/results.html', 
			username=username, 
			role=role, 
			active_page='sizing', 
			active_sub_page='results',
  		)

frontend/webapp/blueprints/tools.py
from flask import Blueprint, render_template, redirect, url_for
from extensions import user_info_wrapper

tools_blueprint = Blueprint('tools', __name__)

@tools_blueprint.route('/')
def home():
	return redirect(url_for('tools.components'))

@tools_blueprint.route('/components/')
@user_info_wrapper
def components(username, role):
	return render_template('tools/components.html', username=username, role=role, active_page='components')

@tools_blueprint.route('/microgrids/', defaults={"id":None})
@tools_blueprint.route('/microgrids/<id>/')
@user_info_wrapper
def grids(username, role, id):
	if id is not None:
		return render_template('tools/grid/single.html', username=username, role=role, active_page='microgrids', id=id)
	return render_template('tools/grid/all.html', username=username, role=role, active_page='microgrids')

@tools_blueprint.route('/powerloads/', defaults={"id":None})
@tools_blueprint.route('/powerloads/<id>/')
@user_info_wrapper
def powerloads(username, role, id):
	if id is not None:
		return render_template('tools/powerload/single.html', username=username, role=role, active_page='powerloads', id=id)
	return render_template('tools/powerload/all.html', username=username, role=role, active_page='powerloads')

frontend/webapp/templates/tools/sizing/compute.html
{% extends 'tools/sizing/layout.html' %}

{% block head2 %}
<link rel="stylesheet" type="text/css" href="/static/css/date-time-picker.css" />
<link rel="stylesheet" type="text/css" href="/static/css/widgets.css" />
{% endblock %}

{% block content3 %}

{% include 'tools/simulate/compute-form.html' %}

<div id="compute-message-container"></div>

{% include 'tools/simulate/widgets.html' %}

{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src="/static/js/helpers-graph.js"></script>
<script src="/static/js/sizing/compute.js"></script>
{% endblock %}

frontend/webapp/templates/tools/sizing/grid.html
{% extends 'tools/sizing/layout.html' %}

{% block head3 %}
<link rel="stylesheet" type="text/css" href="/static/css/grid-single.css" />
<meta name="id" content="{{ id }}" />
{% endblock %}

{% block content3 %}
{% include 'tools/grid/layout-single.html' %}
{% endblock %}

{% block scripts %}

<script src="/static/js/grid/single.js"></script>
{% endblock %}

frontend/webapp/templates/tools/sizing/grids.html
{% extends 'tools/sizing/layout.html' %}

{% block head3 %}
<link rel="stylesheet" type="text/css" href="/static/css/grids.css" />
<link rel="stylesheet" type="text/css" href="/static/css/widgets.css" />
{% endblock %}

{% block content3 %}
{% include 'tools/layout-all-widget.html' %}
{% endblock %}

{% block scripts %}
<script src="/static/js/grid/all.js"></script>
{% endblock %}

frontend/webapp/templates/tools/sizing/layout.html
{% extends 'tools/layout.html' %}

{% block head2 %}
<link rel="stylesheet" type="text/css" href="/static/css/sizing.css" />
<meta name="page-type" content="sizing" />
{% block head3 %}{% endblock %}
{% endblock %}

{% block content2 %}
<div class="submenu">
  <a href="{{ url_for('sizing.grids') }}">
    <div class="submenu-item {% if active_sub_page == 'grids' %}active{% endif %}">Microgrid Sizing Templates</div>
  </a>
  <a href="{{ url_for('sizing.compute') }}">
    <div class="submenu-item {% if active_sub_page == 'compute' %}active{% endif %}">
      Run Analysis
    </div>
  </a>
  <a href="{{ url_for('sizing.results') }}">
    <div class="submenu-item {% if active_sub_page == 'results' %}active{% endif %}" data-subpagename="results">
      Results
    </div>
  </a>
</div>
<div id="sizing">{% block content3 %}{% endblock %}</div>
{% endblock %}

frontend/webapp/templates/tools/sizing/result.html
{% extends 'tools/sizing/layout.html' %}

{% block head2 %}
<link rel="stylesheet" type="text/css" href="/static/css/widgets.css" />
<link rel="stylesheet" type="text/css" href="/static/css/sizing.css" />
{% endblock %}

{% block content3 %}
<div class="d-flex">
  <h3>Result&nbsp;</h3> 
  <h3 id="compute-id">{{ id }}</h3>
</div>

<br/>

<div id="location-name"></div>

<br/>

{% include 'tools/simulate/widgets.html' %}

<br/>
<br/>

<p>
  <button 
    id="download-btn" 
    class="btn btn-primary" 
    onClick="handleExportTable(event)"
    style="display: none;">
    Download Table
  </button>
</p>

<div class="table-label-deficit">Set Sizing Grid Deficit Ratio Limit
          <a href="#" id="deficit-link1" data-deficit="0.0">0.0</a> | 
          <a href="#" id="deficit-link1" data-deficit="0.01">0.01</a> | 
          <a href="#" id="deficit-link2" data-deficit="0.05">0.05</a> |
          <a href="#" id="deficit-link3" data-deficit="0.1">0.1</a>
</div>

<div id="full-screen-loader">
  <div class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>

<div id="sizing-message"></div>

<div id="rotated-table-container">
  <table id="rotated-table-headers" class="table table-bordered">
    <thead><tr></th>
    </thead>
  </table>
  <table id="rotated-table" class="table table-bordered table-hover">
    <thead><tr></th>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>
<br/>

<div class="modal fade" id="confirm-save-result-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirm Save Result Record</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to save <b><span class="record-name"></span></b>?</p>
      </div>
      <div class="modal-footer">
        <button id="save-result-btn" type="button" class="btn btn-primary" onclick="saveToAccount(event)">Save</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
          onClick="closeConfirmSaveModal(event)">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/jquery.nicescroll@3.7.6/jquery.nicescroll.min.js"></script><script src="https://cdn.jsdelivr.net/npm/table2csv@1.1.6/src/table2csv.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src="/static/js/helpers-graph.js"></script>
<script src="/static/js/helpers-table.js"></script>
<script src="/static/js/sizing/result.js"></script>
{% endblock %}

frontend/webapp/templates/tools/sizing/results.html
{% extends 'tools/sizing/layout.html' %}

{% block content3 %}
<div id="results"></div>

<div id="full-screen-loader" style="margin-top: 100px;">
  <div class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>

<div class="modal fade" id="confirm-delete-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirm Delete Result</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete <b><span class="record-name"></span></b>?</p>
      </div>
      <div class="modal-footer">
        <button id="delete-btn" type="button" class="btn btn-danger">Delete</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
          onClick="closeConfirmDeleteModal(event)">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/table2csv@1.1.6/src/table2csv.min.js"></script>
<script src="/static/js/helpers-table.js"></script>
<script src="/static/js/sizing/results.js"></script>
{% endblock %}