frontend/webapp/blueprints/resilience.py
from flask import Blueprint, render_template, redirect, url_for
from extensions import user_info_wrapper

resilience_blueprint = Blueprint('resilience', __name__)

@resilience_blueprint.route('/')
@user_info_wrapper
def home(username, role):
	return redirect(url_for('resilience.compute', method="deterministic"))
	# Replace return redirect with the following to enable multiple methods
	# return render_template(
	# 	'tools/resilience/home.html',
	# 	username=username,
	# 	role=role,
	# 	active_page='resilience',
	# )

@resilience_blueprint.route('/<method>/')
def method_home(method):
	return redirect(url_for('resilience.compute', method=method))

@resilience_blueprint.route('/<method>/disturbances/')
@user_info_wrapper
def disturbances(username, role, method):
	return render_template(
		'tools/resilience/disturbance-repair.html',
		username=username,
		role=role,
		method=method,
		active_page='resilience',
		active_sub_page='disturbances',
		mode='disturbance'
	)

@resilience_blueprint.route('/<method>/disturbances/<id>/')
@user_info_wrapper
def disturbance_detail(username, role, method, id):
	return render_template(
		'tools/resilience/disturbance-repair-detail.html',
		username=username,
		role=role,
		method=method,
		active_page='resilience',
		active_sub_page='disturbances',
		id=id,
		mode='disturbance'
	)

@resilience_blueprint.route('/<method>/repairs/')
@user_info_wrapper
def repairs(username, role, method):
	return render_template(
		'tools/resilience/disturbance-repair.html',
		username=username,
		role=role,
		method=method,
		active_page='resilience',
		active_sub_page='repairs',
		mode='repair'
	)

@resilience_blueprint.route('/<method>/repairs/<id>/')
@user_info_wrapper
def repair_detail(username, role, method, id):
	return render_template(
		'tools/resilience/disturbance-repair-detail.html',
		username=username,
		role=role,
		method=method,
		active_page='resilience',
		active_sub_page='repairs',
		id=id,
		mode='repair'
	)

@resilience_blueprint.route('/<method>/compute/')
@user_info_wrapper
def compute(username, role, method):
	return render_template(
		'tools/resilience/compute.html',
		username=username,
		role=role,
		method=method,
		active_page='resilience',
		active_sub_page='compute'
	)

@resilience_blueprint.route('/<method>/results/', defaults={"id":None})
@resilience_blueprint.route('/<method>/results/<id>/')
@user_info_wrapper
def results(username, role, id, method):
	if id is not None:
		return render_template(
				'tools/resilience/result.html', 
				username=username, 
				role=role, 
				method=method,
				active_page='resilience', 
				active_sub_page='results',
				id=id,
			)
	return render_template(
			'tools/resilience/results.html', 
			username=username, 
			role=role, 
			method=method,
			active_page='resilience', 
			active_sub_page='results',
  		)

frontend/webapp/blueprints/tools.py
from flask import Blueprint, render_template, redirect, url_for
from extensions import user_info_wrapper

tools_blueprint = Blueprint('tools', __name__)

@tools_blueprint.route('/')
def home():
	return redirect(url_for('tools.components'))

@tools_blueprint.route('/components/')
@user_info_wrapper
def components(username, role):
	return render_template('tools/components.html', username=username, role=role, active_page='components')

@tools_blueprint.route('/microgrids/', defaults={"id":None})
@tools_blueprint.route('/microgrids/<id>/')
@user_info_wrapper
def grids(username, role, id):
	if id is not None:
		return render_template('tools/grid/single.html', username=username, role=role, active_page='microgrids', id=id)
	return render_template('tools/grid/all.html', username=username, role=role, active_page='microgrids')

@tools_blueprint.route('/powerloads/', defaults={"id":None})
@tools_blueprint.route('/powerloads/<id>/')
@user_info_wrapper
def powerloads(username, role, id):
	if id is not None:
		return render_template('tools/powerload/single.html', username=username, role=role, active_page='powerloads', id=id)
	return render_template('tools/powerload/all.html', username=username, role=role, active_page='powerloads')

frontend/webapp/templates/tools/resilience/compute-form.html
<form id="form" class="d-flex flex-column compute-form" onsubmit="runAnalysis(event)">
  <div style="display: none;">
    <input type="text" name="method" value="{{ method }}" />
  </div>
  {% include 'tools/simulate/widget-inputs.html' %}
  <br />
  {% include 'tools/simulate/location-inputs.html' %}
  <br />
  <div class="d-flex justify-content-between">
    <div class="row">
      {% include 'tools/simulate/start-end-date-inputs.html' %}
      {% include 'tools/resilience/extend-timeframe-input.html' %}
      {% include 'tools/resilience/num-runs-input.html' %}
    </div>
  </div>
  <br />
  <div class="d-flex justify-content-between">
    <div class="row">
      {% include 'tools/resilience/disturbance-repair-inputs.html' %}
    </div>
    <div class="align-self-end">
      <button id="compute-btn" type="submit" class="btn btn-primary">
        Run Simulation
      </button>
      <button id="load-btn" class="btn btn-primary" type="button" style="display: none;" disabled>
        <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
        Loading...
      </button>
    </div>
  </div>
</form>

<div id="warning-container"></div>

frontend/webapp/templates/tools/resilience/compute.html
{% extends 'tools/resilience/layout.html' %}

{% block head2 %}
<link rel="stylesheet" type="text/css" href="/static/css/simulate.css" />
<link rel="stylesheet" type="text/css" href="/static/css/date-time-picker.css" />
<link rel="stylesheet" type="text/css" href="/static/css/widgets.css" />
{% endblock %}

{% block content3 %}
<h3>Resilience</h3>
<br />
    
{% include 'tools/resilience/compute-form.html' %}

<div id="compute-message-container"></div>

{% include 'tools/resilience/outputs.html' %}
{% include 'tools/resilience/widgets.html' %}

{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src="/static/js/helpers-graph.js"></script>
<script src="/static/js/resilience/helpers.js"></script>
<script src="/static/js/resilience/compute.js"></script>
{% endblock %}

frontend/webapp/templates/tools/resilience/disturbance-repair-detail.html
{% extends 'tools/resilience/layout.html' %}

{% block head3 %}
<link rel="stylesheet" type="text/css" href="/static/css/grid-single.css" />
<meta name="id" content="{{ id }}" />
<meta name="mode" content="{{ mode }}" />
{% endblock %}

{% block content3 %}
<div id="disturbance-repair-detail-root" data-mode="{{ mode }}" class="container-fluid">
  <!-- Back Button -->
  <div class="row mb-3">
    <div class="col">
      <a href="/tools/resilience/{{ method }}/{{ mode }}s/" class="btn btn-secondary text-white">
        <i class="bi bi-arrow-left"></i> Back to {{ mode }}s
      </a>
    </div>
  </div>

  <form id="{{ mode }}-form" onsubmit="saveRecord(event)">
    <!-- Title and Description Section -->
    <div class="row mb-4">
      <div class="col">
        <div class="mb-3">
          <label for="name" class="form-label">Name</label>
          <input type="text" class="form-control" id="name" name="name" required maxlength="32">
        </div>
        <div class="mb-3">
          <label for="description" class="form-label">Description</label>
          <textarea class="form-control" id="description" name="description" maxlength="128"></textarea>
        </div>
      </div>
    </div>

    <!-- Microgrid Selection Section -->
    <div class="row mb-4">
      <div class="col">
        <div class="mb-3">
          <h5>Microgrid: <strong id="grid-name" class="h5"></strong></h5>
        </div>
        <h5>Component Selection</h5>
        <div id="instruction-text" class="text-muted small mb-2">
        </div>
        <div id="microgrid-components" style="display: none;">
          <div class="row" id="components-compact-list">
            <div class="accordion col" id="components-accordion-left"></div>
            <div class="accordion col" id="components-accordion-right"></div>
          </div>
        </div>
      </div>
    </div>

    <!-- Save Button -->
    <div class="row">
      <div class="col">
        <button type="submit" class="btn btn-primary">Save All Changes</button>
      </div>
    </div>
  </form>
</div>

<div id="full-screen-loader" style="display: none;">
  <div class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>
{% endblock %}

{% block scripts3 %}
<script src="/static/js/resilience/disturbance-repair-detail.js"></script>
{% endblock %}

frontend/webapp/templates/tools/resilience/disturbance-repair-inputs.html
<div id="repair-select-container" class="form-group col-md-3">
  <label for="repair-selection">Repair</label>
  <select id="repair-selection" name="repair_id" required class="form-select" aria-label="Repair select"
    aria-describedby="grid-makeup-help">
    <option value="" selected disabled>Select a repair</option>
  </select>
</div>

<div id="disturbance-select-container" class="form-group col-md-3">
  <label for="disturbance-selection">Disturbance</label>
  <select id="disturbance-selection" name="disturbance_id" required class="form-select"
    aria-label="Disturbance select" aria-describedby="disturbance-help">
    <option value="" selected disabled>Select a disturbance</option>
  </select>
</div>

<div class="form-group col-md-4 datetime-container">
  <div class="d-flex">
    <div class="date-container">
      <label for="disturbance_startdate">Disturbance Start</label>
      <input type="text" class="form-control" required id="disturbance_startdate"
        aria-describedby="disturbance_startdate-help" autocomplete="off" disabled>
    </div>
    <div class="time-container">
      <label for="disturbance_starttime"></label>
      <input type="text" class="form-control" required id="disturbance_starttime"
        aria-describedby="disturbance_starttime-help" autocomplete="off" disabled>
    </div>
  </div>
  <div id="disturbance_startdate-feedback" class="invalid-feedback">
    Please enter a valid date (mm/dd/yyyy).
  </div>
</div>

<div id="disturbance-shift-hours-select-container" class="form-group col-md-2">
  <label for="disturbance-shift-hours-selection"># Hours to Shift</label>
  <select id="disturbance-shift-hours-selection" name="disturbance_shift_hours" required class="form-select"
    aria-label="select # hours to shift" aria-describedby="disturbance-shift-hours-help">
    <option value="0" selected>Use default (24 hours)</option>
    <option value="12">12</option>
    <option value="36">36</option>
    <option value="48">48</option>
    <option value="60">60</option>
    <option value="72">72</option>
    <option value="84">84</option>
    <option value="96">96</option>
  </select>
</div>

frontend/webapp/templates/tools/resilience/disturbance-repair.html
{% extends 'tools/resilience/layout.html' %}

{% block head3 %}
<link rel="stylesheet" type="text/css" href="/static/css/widgets.css" />
{% endblock %}

{% block content3 %}
<div id="disturbance-repair-root" data-mode="{{ mode }}">
  {% include 'tools/layout-all-widget.html' %}
</div>
{% endblock %}

{% block scripts3 %}
<script src="/static/js/resilience/helpers.js"></script>
<script src="/static/js/resilience/disturbance-repair.js"></script>
{% endblock %}

frontend/webapp/templates/tools/resilience/extend-timeframe-input.html
<div class="form-group col-md-3">
    <label for="timeframe-selection">Extend timeframe</label>
    <select id='timeframe-selection' name="extend_timeframe_proportion" required class="form-select"
        aria-label="Timeframe select" aria-describedby="timeframe-help">
        <option value="0" selected>0%</option>
        <option value="0.5">50%</option>
        <option value="1.0">100%</option>
    </select>
</div>

frontend/webapp/templates/tools/resilience/home.html
{% extends 'tools/layout.html' %}

{% block head2 %}
<link rel="stylesheet" type="text/css" href="/static/css/simulate.css" />
<link rel="stylesheet" type="text/css" href="/static/css/date-time-picker.css" />
<link rel="stylesheet" type="text/css" href="/static/css/widgets.css" />
{% endblock %}

{% block content2 %}
<h3>Resilience</h3>
<br />
    
<div>Which resilience analysis method would you like to use?</div>
<div><a href="deterministic/">Basic (recommended)</a></div>
<div><a href="stochastic/">Advanced</a></div>
{% endblock %}

frontend/webapp/templates/tools/resilience/layout.html
{% extends 'tools/layout.html' %}

{% block head2 %}
{% block head3 %}{% endblock %}
{% endblock %}

{% block content2 %}
{% if method in [ 'stochastic', 'deterministic' ] %}
<div class="submenu">
  <a href="{{ url_for('resilience.disturbances', method=method) }}">
    <div class="submenu-item {% if active_sub_page == 'disturbances' %}active{% endif %}">
      Disturbances
    </div>
  </a>
  <a href="{{ url_for('resilience.repairs', method=method) }}">
    <div class="submenu-item {% if active_sub_page == 'repairs' %}active{% endif %}" data-subpagename="results">
      Repairs
    </div>
  </a>
  <a href="{{ url_for('resilience.compute', method=method) }}">
    <div class="submenu-item {% if active_sub_page == 'compute' %}active{% endif %}">Run Analysis</div>
  </a>
  <a href="{{ url_for('resilience.results', method=method) }}">
    <div class="submenu-item {% if active_sub_page == 'results' %}active{% endif %}">Results</div>
  </a>
</div>
<div id="method" style="display: none;">{{ method }}</div>
<div id="method-type" style="display: none;">
  {% if method in [ 'stochastic' ] %}no-wait{% else %}wait{% endif %}
</div>

{% block content3 %}{% endblock %}
{% else %}
<div class="alert">You are attempting to access a resilience method that does not exist. Please check the URL.</div>
{% endif %}
{% endblock %}

{% block scripts %}
{% block scripts3 %}{% endblock %}
{% endblock %}

frontend/webapp/templates/tools/resilience/num-runs-input.html
{% if method == 'stochastic' %}
<div class="form-group col-md-2">
    <label for="num-runs">Num runs</label>
    <input type="number" min="1" max="500" value="1" step="1" class="form-control" name="num_runs" required
        id="num-runs" aria-describedby="num_runs-help" autoComplete="off" />
</div>
{% endif %}

frontend/webapp/templates/tools/resilience/outputs.html
<div id="results-container" class="results-hidden" style="display: block;">
  <div id="location-name"></div>
  <div id="disturbance"></div>
  <div id="disturbance-start"></div>
  <div id="repair"></div>
  <div id="extend-timeframe"></div>
  <div id="num-shift-hours"></div>
  <div id="num-runs"></div>
  <br/>
  <div id="metrics"></div>
  <div id="health-gauges"></div>
  </br>
</div>

frontend/webapp/templates/tools/resilience/result.html
{% extends 'tools/resilience/layout.html' %}

{% block head2 %}
<link rel="stylesheet" type="text/css" href="/static/css/widgets.css" />
{% endblock %}

{% block content3 %}
<div class="d-flex">
  <h3>Result&nbsp;</h3> 
  <h3 id="compute-id">{{ id }}</h3>
</div>

{% include 'tools/resilience/outputs.html' %}
<h4 class="mb-3">Analysis Inputs:</h4>
{% include 'tools/resilience/widgets.html' %}

{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/table2csv@1.1.6/src/table2csv.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src="/static/js/helpers-graph.js"></script>
<script src="/static/js/helpers-table.js"></script>
<script src="/static/js/resilience/helpers.js"></script>
<script src="/static/js/resilience/result.js"></script>
{% endblock %}

frontend/webapp/templates/tools/resilience/results.html
{% extends 'tools/resilience/layout.html' %}

{% block content3 %}
<div id="results"></div>

<div id="full-screen-loader" style="margin-top: 100px;">
  <div class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>

<div class="modal fade" id="confirm-delete-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirm Delete Result</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete <b><span class="record-name"></span></b>?</p>
      </div>
      <div class="modal-footer">
        <button id="delete-btn" type="button" class="btn btn-danger">Delete</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
          onClick="closeConfirmDeleteModal(event)">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/table2csv@1.1.6/src/table2csv.min.js"></script>
<script src="/static/js/helpers-table.js"></script>
<script src="/static/js/resilience/results.js"></script>
{% endblock %}

frontend/webapp/templates/tools/resilience/widgets.html
{% include 'tools/simulate/widgets.html' %}
<br/>
<div class="d-flex widget-container">
  <div id="disturbance-card" class="widget"></div>
  <div id="repair-card" class="widget"></div>
  <div id="run-parameters-card" class="widget"></div>
</div>