frontend/webapp/blueprints/resilience.py
from flask import Blueprint, render_template, redirect, url_for
from extensions import user_info_wrapper

resilience_blueprint = Blueprint('resilience', __name__)

@resilience_blueprint.route('/')
@user_info_wrapper
def home(username, role):
	return redirect(url_for('resilience.compute', method="deterministic"))
	# Replace return redirect with the following to enable multiple methods
	# return render_template(
	# 	'tools/resilience/home.html',
	# 	username=username,
	# 	role=role,
	# 	active_page='resilience',
	# )

@resilience_blueprint.route('/<method>/')
def method_home(method):
	return redirect(url_for('resilience.compute', method=method))

@resilience_blueprint.route('/<method>/disturbances/')
@user_info_wrapper
def disturbances(username, role, method):
	return render_template(
		'tools/resilience/disturbance-repair.html',
		username=username,
		role=role,
		method=method,
		active_page='resilience',
		active_sub_page='disturbances',
		mode='disturbance'
	)

@resilience_blueprint.route('/<method>/disturbances/<id>/')
@user_info_wrapper
def disturbance_detail(username, role, method, id):
	return render_template(
		'tools/resilience/disturbance-repair-detail.html',
		username=username,
		role=role,
		method=method,
		active_page='resilience',
		active_sub_page='disturbances',
		id=id,
		mode='disturbance'
	)

@resilience_blueprint.route('/<method>/repairs/')
@user_info_wrapper
def repairs(username, role, method):
	return render_template(
		'tools/resilience/disturbance-repair.html',
		username=username,
		role=role,
		method=method,
		active_page='resilience',
		active_sub_page='repairs',
		mode='repair'
	)

@resilience_blueprint.route('/<method>/repairs/<id>/')
@user_info_wrapper
def repair_detail(username, role, method, id):
	return render_template(
		'tools/resilience/disturbance-repair-detail.html',
		username=username,
		role=role,
		method=method,
		active_page='resilience',
		active_sub_page='repairs',
		id=id,
		mode='repair'
	)

@resilience_blueprint.route('/<method>/compute/')
@user_info_wrapper
def compute(username, role, method):
	return render_template(
		'tools/resilience/compute.html',
		username=username,
		role=role,
		method=method,
		active_page='resilience',
		active_sub_page='compute'
	)

@resilience_blueprint.route('/<method>/results/', defaults={"id":None})
@resilience_blueprint.route('/<method>/results/<id>/')
@user_info_wrapper
def results(username, role, id, method):
	if id is not None:
		return render_template(
				'tools/resilience/result.html', 
				username=username, 
				role=role, 
				method=method,
				active_page='resilience', 
				active_sub_page='results',
				id=id,
			)
	return render_template(
			'tools/resilience/results.html', 
			username=username, 
			role=role, 
			method=method,
			active_page='resilience', 
			active_sub_page='results',
  		)

frontend/webapp/blueprints/simulate.py
from flask import Blueprint, render_template, redirect, url_for
from extensions import user_info_wrapper

simulate_blueprint = Blueprint('simulate', __name__)

@simulate_blueprint.route('/')
def home():
	return redirect(url_for('simulate.compute'))

@simulate_blueprint.route('/compute/')
@user_info_wrapper
def compute(username, role):
	return render_template(
		'tools/simulate/compute.html', 
		username=username, 
		role=role, 
		active_page='simulate', 
		active_sub_page='compute'
	)

@simulate_blueprint.route('/results/')
@user_info_wrapper
def results(username, role):
	return render_template(
			'tools/simulate/results.html', 
			username=username, 
			role=role, 
			active_page='simulate', 
			active_sub_page='results',
  		)

frontend/webapp/blueprints/sizing.py
from flask import Blueprint, render_template, redirect, url_for
from extensions import user_info_wrapper

sizing_blueprint = Blueprint('sizing', __name__)

@sizing_blueprint.route('/')
def home():
	return redirect(url_for('sizing.compute'))

@sizing_blueprint.route('/microgrids/', defaults={"id":None})
@sizing_blueprint.route('/microgrids/<id>/')
@user_info_wrapper
def grids(username, role, id):
	if id is not None:
		return render_template(
			'tools/sizing/grid.html', 
			username=username, 
			role=role, 
			active_page='sizing',
			active_sub_page='grids',
			id=id,
		)
	return render_template(
		'tools/sizing/grids.html',
		username=username, 
		role=role, 
		active_page='sizing',
		active_sub_page='grids'
  	)

@sizing_blueprint.route('/compute/')
@user_info_wrapper
def compute(username, role):
	return render_template(
		'tools/sizing/compute.html', 
		username=username, 
		role=role, 
		active_page='sizing', 
		active_sub_page='compute'
	)

@sizing_blueprint.route('/results/', defaults={"id":None})
@sizing_blueprint.route('/results/<id>/')
@user_info_wrapper
def results(username, role, id):
	if id is not None:
		return render_template(
				'tools/sizing/result.html', 
				username=username, 
				role=role, 
				active_page='sizing', 
				active_sub_page='results',
				id=id,
			)
	return render_template(
			'tools/sizing/results.html', 
			username=username, 
			role=role, 
			active_page='sizing', 
			active_sub_page='results',
  		)

frontend/webapp/blueprints/tools.py
from flask import Blueprint, render_template, redirect, url_for
from extensions import user_info_wrapper

tools_blueprint = Blueprint('tools', __name__)

@tools_blueprint.route('/')
def home():
	return redirect(url_for('tools.components'))

@tools_blueprint.route('/components/')
@user_info_wrapper
def components(username, role):
	return render_template('tools/components.html', username=username, role=role, active_page='components')

@tools_blueprint.route('/microgrids/', defaults={"id":None})
@tools_blueprint.route('/microgrids/<id>/')
@user_info_wrapper
def grids(username, role, id):
	if id is not None:
		return render_template('tools/grid/single.html', username=username, role=role, active_page='microgrids', id=id)
	return render_template('tools/grid/all.html', username=username, role=role, active_page='microgrids')

@tools_blueprint.route('/powerloads/', defaults={"id":None})
@tools_blueprint.route('/powerloads/<id>/')
@user_info_wrapper
def powerloads(username, role, id):
	if id is not None:
		return render_template('tools/powerload/single.html', username=username, role=role, active_page='powerloads', id=id)
	return render_template('tools/powerload/all.html', username=username, role=role, active_page='powerloads')

frontend/webapp/templates/tools/components.html
{% extends 'tools/layout.html' %}

{% block head2 %}
<link rel="stylesheet" type="text/css" href="/static/css/components.css" />
{% endblock %}

{% block content2 %}
  
<div class="row">
  <div class="col">
    <h3 id="components-title">Components</h3>
  </div>
  <div class="col">
    <button type="button" class="btn btn-primary float-end new" data-type="component"
      onclick="handleUserQuotaCheck(event)">New +</button>
  </div>
</div>

<br />

<div class="form-check form-switch" id="compact-view-container">
  <input class="form-check-input" type="checkbox" id="compact-view-input"
    onchange="handleCompactViewToggle(event)">
  <label class="form-check-label" for="compact-view-input">Compact View</label>
</div>

<br />

<div id="full-screen-loader">
  <div class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>

<div class="full-width-list" id="list"></div>

<div class="row" id="components-compact-list" style="display: none;">
  <div class="accordion col" id="components-accordion-left"></div>
  <div class="accordion col" id="components-accordion-right"></div>
</div>

<div class="row">
  <div id="no-components-message" style="display: none;">You don't have any components yet.</div>
</div>

<div class="modal fade" id="confirm-delete-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirm Deletion</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete <b><span class="name"></span></b>? This action cannot be
          undone.</p>
      </div>
      <div class="modal-footer">
        <button id="delete-btn" type="button" class="btn btn-danger delete">Delete</button>
        <button 
          id="close-confirm-delete-btn" 
          type="button" 
          class="btn btn-secondary"
          onClick="closeConfirmDeleteModal(event)">
          Cancel
        </button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="new-modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New Component</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="new-form" class="form-control needs-validation" onsubmit="create(event)">
          <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input 
              type="name" 
              name="name" 
              class="form-control" 
              id="name" 
              required="true"
              autocomplete="off"
              maxlength="32">
            <br />
            <label for="description" class="form-label">Description</label>
            <textarea id="description" type="description" name="description" name="description" class="form-control"
              maxlength="128"></textarea>
          </div>
          <div class="mb-3">
            <label for="type-select" class="form-label">Type</label>
            <select name="type" id="type-select" class="form-select" required="true"
              onchange="selectComponentType(event)">
              <option value="" disabled selected>Select component type</option>
            </select>
          </div>
          <div id="new-specs" class="mb-3"></div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">
              Create
            </button>
            <button 
              id="cancel-add-btn" 
              type="button" 
              class="btn btn-secondary" 
              onClick="handleCloseCreateNewModal(event)">
              Cancel
            </button>
          </div>
          <div id="new-error-alert" class="alert alert-danger alert-dismissible" role="alert"
            style="display: none;">
            <span></span>
            <button id="new-error-dismiss-btn" type="button" class="btn-close" aria-label="Close"
              onclick="dismissAddComponentErrorAlert(event)"></button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}


{% block scripts %}
<script src="/static/js/components.js"></script>
{% endblock %}

frontend/webapp/templates/tools/layout-all-widget.html
<div class="row">
  <div class="col">
    <h3 id="title"></h3>
  </div>
  <div class="col">
    <button id="new-modal-open-btn" type="button" class="btn btn-primary float-end new"
      onclick="handleUserQuotaCheck(event)">New +</button>
  </div>
</div>

<br/> 

<div id="full-screen-loader">
  <div class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>

<div id="list" class="d-flex widget-container"></div>

<br />

<div class="row">
  <div id="no-records-message" style="display: none;">
    You don't have any 
    {% if active_page == 'sizing' %}microgrid sizing templates
    {% elif active_page == 'microgrids'%}microgrids
    {% elif active_page == 'powerloads'%}Powerloads
    {% elif mode == 'disturbance' %}disturbances
    {% elif mode == 'repair' %}repairs
    {% endif %} yet.
  </div>
</div>

<div class="modal fade" id="new-modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          New 
          {% if active_page == 'sizing' %}Microgrid Sizing Template
          {% elif active_page == 'microgrids'%}Microgrid
          {% elif active_page == 'powerloads'%}Powerloads
          {% elif mode == 'disturbance' %}Disturbance
          {% elif mode == 'repair' %}Repair
          {% endif %}
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {% if active_page == 'powerloads'%}
        <form id="new-form" class="form-control needs-validation" onsubmit="onUploadClicked(event)">
          <div class="mb-3">
            <span>
              Upload a new powerload <i id="info-btn" class="bi bi-info-circle info-btn"
                onclick="openPowerloadInfoModal(event)"></i>
            </span>
            <input class="form-control" type="file" id="file" accept=".csv" required
              onchange="handleUpload(event)">
          </div>
          <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input class="form-control" name="name" id="name" maxlength="32" autocomplete="off" required>
          </div>
          <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <textarea id="description" name="description" class="form-control"
              maxlength="128"></textarea>
          </div>
          <div class="modal-footer">
            <button id="upload-btn" type="submit" class="btn btn-primary align-self-end">
              Upload
            </button>
            <button id="upload-load-btn" class="btn btn-primary align-self-end" type="button" style="display: none;"
              disabled>
              <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
              Loading...
            </button>
            <button id="cancel-add-btn" type="button" class="btn btn-secondary" onClick="closeCreateNewModal(event)">
              Cancel
            </button>
          </div>
          <div id="new-error"></div>
          <div id="preview-container">
            <div id="preview" class="powerload-table-container"></div>
          </div>
        </form>
        {% else %}
        <form id="new-form" onsubmit="create(event)">
          <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input id="name" name="name" class="form-control" maxlength="32" autocomplete="off" required>
            <br />
            <label for="description" class="form-label">Description</label>
            <textarea id="description" name="description" class="form-control" maxlength="128"></textarea>
            {% if mode in ['disturbance', 'repair'] %}
            <br />
            <label for="microgrid-select" class="form-label">Microgrid</label>
            <select id="microgrid-select" name="gridId" class="form-select" required>
              <option value="" selected disabled>Select a microgrid</option>
            </select>
            {% endif %}
          </div>
          <div class="modal-footer">
            <button id="create-btn" type="submit" class="btn btn-primary">Create</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
              Cancel
            </button>
          </div>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="confirm-delete-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirm Deletion</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete <b><span class="name"></span></b>? This action cannot be undone.</p>
      </div>
      <div class="modal-footer">
        <button id="delete-btn" type="button" class="btn btn-danger delete">
          Delete
        </button>
        <button 
          id="close-confirm-delete-btn" 
          type="button" 
          class="btn btn-secondary" 
          data-bs-dismiss="modal" 
          onClick="closeConfirmDeleteModal(event)">
          Cancel
        </button>
      </div>
    </div>
  </div>
</div>

{% if active_page == 'powerloads'%}
<div class="modal fade" id="file-info-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Powerload Files</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>The powerload file must be in CSV format with exactly two columns where the first column is time in hours and
          the second column is power in kilowatts. The file may contain an optional header row.</p>
        <p>Here are two example files both containing the powerload data in the application guest account: </p>
        <a href="/static/data/powerload_example_no_header.csv">CSV example file without headers</a>
        <br />
        <a href="/static/data/powerload_example_with_header.csv">CSV example file with headers</a>
      </div>
    </div>
  </div>
</div>
<div id="powerload-temp-graph"></div>
{% endif %}

frontend/webapp/templates/tools/layout.html
{% extends 'layout.html' %}

{% block head %}
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/static/css/tools.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/timepicker@1.14.1/jquery.timepicker.css">
<!--Jquery UI and other Scripts-->
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/timepicker@1.14.1/jquery.timepicker.js"></script>
<script src="https://d3js.org/d3.v6.min.js"></script>
<script src="https://cdn.sheetjs.com/xlsx-0.19.1/package/dist/xlsx.full.min.js"></script>
<!--Inter-Connection scripts-->
<!-- see https://docs.sheetjs.com/docs/api/ -->
<script src="/static/js/paths.js"></script>
<script src="/static/js/helpers-datetime.js"></script>
<script src="/static/js/helpers.js"></script>
<script src="/static/js/mobile-nav.js"></script>
{% block head2 %}{% endblock %}
{% endblock %}

{% block content %}
<div id="tool-navigation">
  <div class="container">
    <div class="nav position-relative" id="nav-tab">
      <a href="{{ url_for('tools.components') }}">
        <div class="nav-item {% if active_page == 'components' %}active{% endif %}" id="nav-components-tab"
          onclick="toggleMobileToolNavMenu(this, event)" aria-selected="true">
          <span>Components</span>
          <i class="bi bi-caret-right"></i>
          <i class="bi bi-caret-down"></i>
        </div>
      </a>
      <a href="{{ url_for('tools.grids') }}">
        <div class="nav-item {% if active_page == 'microgrids' %}active{% endif %}" id="nav-microgrids-tab"
          onclick="toggleMobileToolNavMenu(this, event)">
          <span>Microgrids</span>
          <i class="bi bi-caret-right"></i>
          <i class="bi bi-caret-down"></i>
        </div>
      </a>
      <a href="{{ url_for('tools.powerloads') }}">
        <div class="nav-item {% if active_page == 'powerloads' %}active{% endif %}" id="nav-powerloads-tab"
          onclick="toggleMobileToolNavMenu(this, event)">
          <span>Powerloads</span>
          <i class="bi bi-caret-right"></i>
          <i class="bi bi-caret-down"></i>
        </div>
      </a>
      <a href="{{ url_for('simulate.home') }}">
        <div class="nav-item {% if active_page == 'simulate' %}active{% endif %}" id="nav-simulate-tab"
          onclick="toggleMobileToolNavMenu(this, event)">
          <span>Simulate</span>
          <i class="bi bi-caret-right"></i>
          <i class="bi bi-caret-down"></i>
        </div>
      </a>
      {% if role and role != 'Guest' %}
        <a href="{{ url_for('sizing.home') }}">
          <div class="nav-item {% if active_page == 'sizing' %}active{% endif %}" id="nav-sizing-tab"
            onclick="toggleMobileToolNavMenu(this, event)">
            <span>Sizing</span>
            <i class="bi bi-caret-right"></i>
            <i class="bi bi-caret-down"></i>
          </div>
        </a>
        <a href="{{ url_for('resilience.home') }}">
          <div class="nav-item {% if active_page == 'resilience' %}active{% endif %}" id="nav-resilience-tab"
            onclick="toggleMobileToolNavMenu(this, event)">
            <span>Resilience</span>
            <i class="bi bi-caret-right"></i>
            <i class="bi bi-caret-down"></i>
          </div>
        </a>
      {% endif %}
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <div id="tool-error"></div>
    <div class="content" id="content">
      {% block content2 %}{% endblock %}
    </div>
  </div>
</div>

{% block scripts %}{% endblock %}

{% endblock %}