frontend/webapp/blueprints/tools.py
from flask import Blueprint, render_template, redirect, url_for
from extensions import user_info_wrapper

tools_blueprint = Blueprint('tools', __name__)

@tools_blueprint.route('/')
def home():
	return redirect(url_for('tools.components'))

@tools_blueprint.route('/components/')
@user_info_wrapper
def components(username, role):
	return render_template('tools/components.html', username=username, role=role, active_page='components')

@tools_blueprint.route('/microgrids/', defaults={"id":None})
@tools_blueprint.route('/microgrids/<id>/')
@user_info_wrapper
def grids(username, role, id):
	if id is not None:
		return render_template('tools/grid/single.html', username=username, role=role, active_page='microgrids', id=id)
	return render_template('tools/grid/all.html', username=username, role=role, active_page='microgrids')

@tools_blueprint.route('/powerloads/', defaults={"id":None})
@tools_blueprint.route('/powerloads/<id>/')
@user_info_wrapper
def powerloads(username, role, id):
	if id is not None:
		return render_template('tools/powerload/single.html', username=username, role=role, active_page='powerloads', id=id)
	return render_template('tools/powerload/all.html', username=username, role=role, active_page='powerloads')

frontend/webapp/blueprints/toplevel.py
from flask import Blueprint, render_template
import configparser
from extensions import user_info_wrapper, clear_session_data

_CONFIG_INI = configparser.ConfigParser()
_CONFIG_INI.read("config.ini")
_CUI_COMPONENT = _CONFIG_INI.get("CUI", "COMPONENT", fallback="")
_CUI_OFFICE = _CONFIG_INI.get("CUI", "OFFICE", fallback="")
_CUI_CATEGORIES = _CONFIG_INI.get("CUI", "CATEGORIES", fallback="")
_CUI_LIMITED_DISSEMINATION = _CONFIG_INI.get("CUI", "LIMITED_DISSEMINATION", fallback="")

toplevel_blueprint = Blueprint('toplevel', __name__)

@toplevel_blueprint.route('/')
@user_info_wrapper
def home(username, role):
	return render_template('index.html', username=username, role=role,
			cui_component=_CUI_COMPONENT,
			cui_office=_CUI_OFFICE,
			cui_categories=_CUI_CATEGORIES,
			cui_limited_dissemination=_CUI_LIMITED_DISSEMINATION
	)

@toplevel_blueprint.route('/clear_session/')
def clear_session():
	return clear_session_data(login_redirect=True)

frontend/webapp/templates/index.html
{% extends 'layout.html' %}
   
{% block head %}
<title>Microgrid Planner</title>
{% endblock %}

{% block title %}Microgrid{% endblock %}

{% block content %}

<div class="container content">
  <section id="intro" class="home">
      <h2>A Suite of Tools</h2>
      <p>
          Microgrid Planner is a peer-reviewed open-source suite of web tools designed to assist with
          the early stages of microgrid planning. Our technology stack includes Python, MySQL, Flask, JavaScript, jQuery, Bootstrap, HTML, CSS, and Docker. We are distributing our codebase as open-source software for two reasons: (1) allow others in the scientific community to deploy microgrid planning methods that would otherwise be purely methodological research endeavors, due to a lack of resources to develop the infrastructure required for deployment; and (2) encourage others to contribute to the future development of our suite of tools. We welcome both feedback and collaboration opportunities. 
      </p>
      <p>
        Note: registering an account is required to access the complete set of software features; the guest account demonstrates a limited number of the available features.
      </p>
  </section>

  <section id="video" class="home">
    <h3>Intro Video</h3>
    <iframe 
        src="https://player.vimeo.com/video/1116844449" 
        width="640" 
        height="360" 
        frameborder="0" 
        allow="autoplay; fullscreen; picture-in-picture" 
    >
    </iframe>
  </section>
  
  <section id="citation" class="home">
    <h2>Citing our Platform</h2>
    <p>
        To cite this software, please cite both our paper <a href="https://doi.org/10.1287/ijoc.2023.0336" target="_blank">Microgrid Planner: An Open-Source Software Platform</a> published in <i>INFORMS Journal on Computing</i> and its corresponding <a href="https://github.com/INFORMSJoC/2023.0336" target="_blank">GitHub repository</a>.
    </p>
  </section>

  <section id="contributors" class="home">
    <h3>Software Contributors</h3>
    <p>
        Microgrid Planner</a> was developed by
        <ul>
            <li><a href="https://faculty.nps.edu/dreich/" target="_blank">
                Daniel Reich</a>, 2020-present</li>
            <li><a href="https://www.linkedin.com/in/leah-frye/" target="_blank">
                Leah Frye</a>, 2022-2024</li>
        </ul>
    </p>
    <p>
        with contributions from
        <ul>
            <li><a href="https://www.linkedin.com/in/hyatt-moore-iv-382178a/" target="_blank">
                Hyatt Moore</a>, proof of concept JavaScript and MySQL contributor, 2021-2022</li>
            <li><a href="https://www.linkedin.com/in/bruce-v-chiarelli-64853917/" target="_blank">
                Bruce Chiarelli</a>, Docker contributor and deployment support 2021-2023</li>
            <li><a href="https://www.linkedin.com/in/jeffhaferman/" target="_blank">
                Jeff Haferman</a>, Naval Postgraduate School High-Performance Computing support, 2023-present</li>
            <li><a href="https://www.linkedin.com/in/philip-mccullick-6529977/" target="_blank">
                Philip McCullick</a>, Docker contributor and deployment support 2023-present</li>
            <li>Eldor Magat, deployment support 2024-2025</li>
            <li><a href="https://www.linkedin.com/in/taylorjconn/" target="_blank">
                Taylor Conn</a>, frontend contributor, 2024-2025</li>
            <li><a href="https://www.linkedin.com/in/richard-alves/" target="_blank">
                Richard Alves</a>, photovoltaic and wind modeling contributor, 2024-present</li>
            <li>Captain Dylan Bruns, home page demo video, 2025</li>
            <li><a href="https://www.linkedin.com/in/joseph-martineau/" target="_blank">
                Joseph Martineau</a>, deployment support 2025-present</li>
            <li><a href="https://www.linkedin.com/in/craigvershaw/" target="_blank">
                Craig Vershaw</a>, networking support for CAC authentication 2026-present</li>
        </ul>
        Our front-end authentication code is a modified and extended version of the <a href="https://codeshack.io/package/php/advanced-secure-login-registration-system/" target="_blank">Advanced Secure Login & Registration System</a> developed by <a href="https://codeshack.io/" target="_blank">CodeShack</a>.
    </p>
  </section>

  <section id="release" class="home">
    <h3>Release Notes</h3>
    <p class="multiple-paragraphs">
        Version 3.1 - February 2026
        <ul>
            <li>Common Access Card (CAC) authentication</li>
            <li>Consent banner and labels for Controlled Unclassified Information (CUI)</li>
            <li>Configuration options for enabling CAC, and deactivating local login with username and password</li>
        </ul>
    </p>
    <p class="multiple-paragraphs">
        Version 3.0 - August 2025
        <ul>
            <li>Resilience analysis method</li>
            <li>Framework for supporting multiple resilience analysis methods</li>
            <li>Disturbance and repair data collection, handling, and visualization</li>
            <li>JavaScript helper methods for waiting for analyses to complete, submitting analyses, and retrieving results</li>
            <li>GUI updates, including improved date/time input handling</li>
            <li>Refactored code with improved organization and efficiency</li>
            <li>Upgraded password authentication from SHA-1 to Argon2</li>
            <li>Updated package installation for compliance with PEP 517/518 standards</li>
        </ul>
    </p>
    <p class="multiple-paragraphs">
        Version 2.1 - June 2024
        <ul>
            <li>Integrated <a href="https://sam.nrel.gov/software-development-kit-sdk/pysam.html" target="_blank">PySAM from NREL</a> for photovoltaic modeling</li>
        </ul>
    </p>
    <p class="multiple-paragraphs">
        Version 2.0 - April 2024
        <ul>
            <li>Location-based analyses</li>
            <li>Enhanced solar and wind models</li>
            <li>Integration with weather data from the <a href="https://nsrdb.nrel.gov/" target="_blank">National Solar Radiation Database (NSRDB)</a>, hosted by the <a href="https://www.nrel.gov/" target="_blank">National Renewable Energy Laboratory (NREL)</a></li>
            <li><a href="https://slurm.schedmd.com/" target="_blank">Slurm</a> job queuing to enable computationally intensive algorithms</li>
            <li>Automated microgrid sizing method</li>
            <li>Simulation history with caching</li>
            <li>Selectable energy management systems</li>
            <li>Improved power load data handling</li>
            <li>Updated GUI with widgets</li>
            <li>Refactored code with improved organization and efficiency</li>
        </ul>
    </p>
    <p class="multiple-paragraphs">
        Version 1.1 - September 2023
        <ul>
            <li>Updated GUI</li>
            <li>Refactored code with improved organization and efficiency</li>
        </ul>
    </p>
    <p class="multiple-paragraphs">
        Version 1.0 - March 2023
        <ul>
            <li>User accounts with authentication</li>
            <li>User-defined components for diesel generators, photovoltaic systems, wind turbines and battery energy storage systems</li>
            <li>User-defined grids</li>
            <li>Upload and storage of powerload data</li>
            <li>Integration of Version 0.0 simulation methods with user-defined grids and powerload data</li>
            <li>Simulation method for measuring resilience of user-defined grids, using user-defined disturbance probabilities and repair times</li>
            <li>Data farming method for performing sensitivity analysis on grids (offline only)</li>
        </ul>
    </p>
    <p>
        Version 0.0 - November 2021
        <ul>
            <li>Simulation with parameter inputs for one diesel generator, one photovoltaic system, one wind turbine and one battery energy storage system</li>
            <li>Simulation with parameter inputs for multiple diesel generators, photovoltaic systems, wind turbines and battery energy storage systems (offline only)</li>
            <li>Distributed energy resource sizing method for one diesel generator, one photovoltaic system and one battery energy storage system (offline only)</li>
        </ul>
    </p>
  </section>

  <section id="about" class="home">
    <h3>Future Release Plans</h3>
    <p>
        Additional features planned for release in upcoming updates include
        <ul>
          <li>Cost modeling</li>
          <li>Enhanced methods for distributed energy resource sizing</li>
      </ul>
    </p>
  </section>

  {% if include_cui %}
    <section class="cui-di-block" aria-label="CUI Designation Indicator">
        <div><strong>Controlled by:</strong>{{ cui_component }} / {{ cui_office }}</div>
        {% if cui_categories %}
            <div><strong>CUI Category:</strong> {{ cui_categories }}</div>
        {% endif %}
        <div><strong>Limited Dissemination Control:</strong> {{ cui_limited_dissemination }}</div>
        <div><strong>POC:</strong> {{ admin_email }}</div>
    </section>
  {% endif %}

</div>
{% endblock %}

frontend/webapp/templates/layout.html
<!DOCTYPE html>
<html class="h-100">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width,minimum-scale=1">
		<title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">
    {% if include_cui %}
      <link rel="stylesheet" href="{{ url_for('static', filename='css/cui.css') }}">
    {% endif %}
		<link rel="stylesheet" href="{{ url_for('static', filename='authentication-codeshack/style.css') }}">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous"/>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/WindTurbine.png') }}">
    {% block head %}{% endblock %}
	</head>
	<body class="loggedin d-flex flex-column h-100 {% if role == 'Guest' %}guest{% endif %}" >
    {% if include_cui %}
      <div class="cui-banner cui-banner--top" role="note" aria-label="Controlled Unclassified Information banner">CUI</div>
    {% endif %}
    <main id="app-content">
      <div id="role" style="display: none;">{{ role }}</div>
      <nav class="navtop">
        <div class="container">
          <div class="app-logo-title-container">
            <a href="{{ url_for('toplevel.home') }}">
              <img class="app-logo" src="{{ url_for('static', filename='images/WindTurbine.png') }}"/>
              <h1>Microgrid Planner</h1>
            </a>
          </div>
          
          <button id="mobile-nav-btn" class="btn" onclick="toggleMobileNavMenu(this, event)">
            <i class="bi bi-list"></i>
          </button>

          <div id="navtop-links-container">
            <a href="{{ url_for('tools.home') }}"><i class="fas fa-lightbulb"></i>Tools</a>
            <a href="https://github.com/reichd/MicrogridPlanner" target="_blank"><i class="fas fa-code"></i>Code</a>          
            <a href="{{ url_for('authentication.profile') }}"><i class="fas fa-user-circle"></i>
              {{ username if username else 'guest'}}</a>
            {% if role == 'Admin' %}
              <a href="{{ url_for('authentication.admin') }}"><i class="fas fa-cog"></i>Admin</a>
            {% endif %}
            {% if not username or (username == 'guest' and role != 'Admin') %}
              <a href="{{ url_for('authentication.login') }}"><i class="fas fa-sign-out-alt"></i>Login</a>
            {% else %}
              <a href="{{ url_for('authentication.logout') }}"><i class="fas fa-sign-out-alt"></i>Logout</a>
            {% endif %}
          </div>
        </div>
      </nav>

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      
      {% block content %}{% endblock %}
      
      <div class="toast-container">
        <div id="global-toast" class="toast hide bg-success text-white" role="alert" aria-live="assertive" aria-atomic="true">
          <div class="toast-body">
            <i class="bi bi-check-circle-fill"></i>
            <span class="toast-text"></span>
          </div>
        </div>
      </div>

      <footer class="footer mt-auto py-3 bg-light">
        <div class="container">
          <img class="nps-logo" src="{{ url_for('static', filename='images/nps_logo.png') }}"/>
          <div>
            <span class="text-muted">Site hosted by <a href="https://www.nps.edu" target="_blank">Naval Postgraduate School</a></span>
            <br/>
            <span class="text-muted">Contact <a href="mailto:{{ admin_email }}">{{ admin_email }}</a></span>
          </div>
        </div>
      </footer>
    </main>
    {% if include_cui %}
      <div class="cui-banner cui-banner--bottom" role="note" aria-label="Controlled Unclassified Information footer">CUI</div>
    {% endif %}

    <script>
      // Handles collapsing/expanding main mobile navigation
      const toggleMobileNavMenu = (el, e) => {
        const navMenu = $("#navtop-links-container");
        if (navMenu.hasClass("show-nav-dropdown")) {
          navMenu.removeClass("show-nav-dropdown");
        }
        else {
          navMenu.addClass("show-nav-dropdown");
        }
      }
    </script>
	</body>
</html>